### PR TITLE
add fallbackValue stupport to isEnabled

### PR DESCRIPTION
**Pull request by sveisvei**
cc @ivarconr

### CODE REVIEW

**Comment by ivarconr** [comment]
Oh, this is actually a different solution than I was thinking about. I was thinking of two cases: 

1. unleash is not initialized yet
2. the feature toggle is not defined yet in unleash-server

This could be solved with the following check inside `client.js`:

```js
if (!feature) {
  return defaultValue;
}
```

**Comment by sveisvei** [comment]
this is to solve the point 1).

Can add support for point 2) as well

**Comment by ivarconr** [comment]
not sure if my solution is better though, but it's kinda the way it was solved in the javaclient: 

https://github.com/finn-no/unleash-client-java/blob/master/src/main/java/no/finn/unleash/DefaultUnleash.java#L42

```java
        if (featureToggle == null) {
            return defaultSetting;
        } else if(!featureToggle.isEnabled()) {
            return false;
        }
```

**Comment by ivarconr** [comment]
excellent point!

**Comment by sveisvei** [comment]
Added support for 2 (missing test atm), is this what you think is the complete solution?

**Comment by ivarconr** [comment]
yes, this nails it! :+1: :zap:

**Pull request merged**
